config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  get 'expenses/admin_index'

  resources :expenses

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord

validates_presence_of :expense_type, :amount, :date, :description
belongs_to :user

mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :expenses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  def index
    @expenses = current_user.expenses.order(date: :desc)
    @expenses_total = current_user.expenses.sum(:amount)
  end

  def admin_index
    @expenses = Expense.all
    @expenses_total = Expense.all.sum(:amount)

    if current_user.admin == true
      render 'admin_index'
    else
      render 'index'
    end
  end

  def show
    @expense = Expense.find(params[:id])
  end

  def new
    @expense = current_user.expenses.build
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def create
    @expense = current_user.expenses.build(expense_params)

    if  @expense.save
      redirect_to @expense
    else
      render 'new'
    end
  end

  def update
    @expense = Expense.find(params[:id])

    if @expense.update(expense_params)
      redirect_to @expense
    else
      render 'edit'
    end
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy

    redirect_to expenses_path
  end


  private

  def expense_params
    params.require(:expense).permit(:expense_type, :amount, :date, :description, :image, :user)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/expenses/_form.html.erb
<div align='center'>
<%= form_with model: @expense, local: true do |form| %>

<% if @expense.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@expense.errors.count, "error") %> prohibited
      this expense from being saved:
    </h2>
    <ul>
      <% @expense.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <p>
    <%= form.label :expense_type %><br>
    <%= form.select :expense_type, ['Travel', 'Lunch', 'Dinner', 'Accommodation']%>
  </p>

  <p>
    <%= form.label :amount %><br>
    <%= form.number_field :amount, :step => '0.01' %>
  </p>

  <p>
    <%= form.label :date %><br>
    <%= form.date_select :date %>
  </p>


  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.label :Image %><br>
    <%= form.file_field :image %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>
</div>

app/views/expenses/admin_index.html.erb
<div align='center'>
<h1>Expense Overview</h1>

<table class='table'>
  <tr>
    <th>Expense type</th>
    <th>Amount</th>
    <th>Description</th>
    <th>Date of expense</th>
    <th>Details</th>
    <th>Edit expense</th>
    <th>Delete expense</th>
    <th> User email</th>
  </tr>

  <% @expenses.each do |expense| %>
    <tr>
      <td><%= expense.expense_type %></td>
      <td><%= expense.amount %></td>
      <td><%= expense.description %></td>
      <td><%= expense.date %></td>
      <td><%= link_to 'Show', expense_path(expense) %></td>
      <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
      <td><%= link_to 'Delete', expense_path(expense),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
      <td><%= expense.user.email %></td>
    </tr>
  <% end %>

  <tfoot>
    <tr>
      <td>Total Amount: </td>
      <td>£<%=@expenses_total%></td>
    </tr>
  </tfoot>
</table>

</div>

app/views/expenses/edit.html.erb
<div align='center'>
<h1>Edit expense</h1>

<%= render 'form' %>
</div>

app/views/expenses/index.html.erb
<div align='center'>
<h1>Your expenses</h1>

<table class='table'>
  <tr>
    <th>Expense type</th>
    <th>Amount</th>
    <th>Description</th>
    <th>Date of expense</th>
    <th>Details</th>
    <th>Edit expense</th>
    <th>Delete expense</th>
  </tr>

  <% @expenses.each do |expense| %>
    <tr>
      <td><%= expense.expense_type %></td>
      <td><%= expense.amount %></td>
      <td><%= expense.description %></td>
      <td><%= expense.date %></td>
      <td><%= link_to 'Show', expense_path(expense) %></td>
      <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
      <td><%= link_to 'Delete', expense_path(expense),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>

  <tfoot>
    <tr>
      <td>Total Amount: </td>
      <td>£<%=@expenses_total%></td>
    </tr>
  </tfoot>
</table>

</div>

app/views/expenses/new.html.erb
<h1 align='center'>Add new expense</h1>
<br>
<%= render 'form' %>

app/views/expenses/show.html.erb
<div align='center'>

<h1>Expense Summary</h1>


  <p><strong>Expense type:</strong></p>
  <p><%= @expense.expense_type %></p>


  <p><strong>Amount(£):</strong></p>
  <p><%= @expense.amount %></p>

  <p><strong>Date of expense:</strong></p>
  <p><%= @expense.date %></p>

  <p><strong>Description:</strong></p>
  <p><%= @expense.description %></p>

  <p><strong>Evidence of expense:</strong></p>
    <% if @expense.image.present? %>
      <p><%= image_tag(@expense.image_url.to_s) %></p>
    <% else %>
      <p>No evidence submitted. </p>
    <% end %>

<%= link_to "Your expenses", expenses_path %>

</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue pt-4 mt-4">
<hr>
  <div class="footer-copyright text-center py-3">© 2018 Copyright:
    <%= link_to "Expens.io", root_path %>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation" id='site-navbar'>
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Expens.io", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "Your Expenses", expenses_path, class: "active" %></li>
          <li><%= link_to "New Expense", new_expense_path, class: "active" %></li>
          <% if current_user.admin == true %>
            <li><%= link_to "Expenses Overview", expenses_admin_index_path %>
          <% end %>
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Log In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expensio</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container-fluid">
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
 </div>

 <div class="container-fluid">
   <%= yield %>
 </div>

 <%= render 'layouts/footer' %>
  </body>
</html>

app/views/welcome/index.html.erb
<div align='center'>
  <div id='home-content'>
    <div id='home-text'>
      <h1>Expens.io</h1>

      <h3>Helping you to keep track of your work expenses</h3><br>
    </div>
  </div>


  <p>Expens.io is here to help you keep on top of your expenses. Sign up today and
     see what we can do for you.</p><br>

  <div>
    <% if !user_signed_in? %>
      <a id='site-buttons' href="/users/sign_up" class="btn btn-primary">Create an account</a>
      <a id='site-buttons' href="/users/sign_in" class="btn btn-primary">Log in</a>
    <% else %>
      <a id='site-buttons' href="/expenses" class="btn btn-primary">Your expenses</a>
    <% end %>
  </div>

</div>